name: Build and Push Buildozer Docker Image

on:
  push:
    branches:
      - main # Trigger on push to main
    paths:
      - 'Dockerfile' # Only trigger if Dockerfile changes
  workflow_dispatch: # Allow manual trigger

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required to push to GitHub Container Registry

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: . # Look for Dockerfile in the root of the repo
        push: true
        tags: ghcr.io/${{ github.repository }}/buildozer-env:latest # Image name and tag
        cache-from: type=gha,scope=buildozer-env-cache # Use GitHub Actions cache for layers
        cache-to: type=gha,mode=max,scope=buildozer-env-cache
        
